apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reposilite.fullname" . }}
  labels:
    {{- include "reposilite.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "reposilite.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reposilite.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "reposilite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
{{- if .Values.reposilite.config_as_secret }}
      volumes:
      - name: reposilite-config
        secret:
          secretName: reposilite-config
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
# reposilite will not work with config on a ro fs
{{- if .Values.reposilite.config_as_secret }}
          command: ["/bin/sh", "-c"]
          args: ["cp -vf /tmp/reposilite.cdn /app/data/reposilite.cdn && java $JAVA_OPTS -jar reposilite.jar -wd=/app/data $REPOSILITE_OPTS -lc=/app/data/reposilite.cdn --token reposilite:{{ randAlphaNum 16}}"]
 {{- end }}
          tty: true
          stdin: true
          volumeMounts:
{{- if .Values.reposilite.config_as_secret }}
          - name: reposilite-config
            mountPath: /tmp/reposilite.cdn
            readOnly: false
            subPath: reposilite.cdn
{{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
{{- if not .Values.probes.disabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
