apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reposilite.fullname" . }}-config
  labels:
    {{- include "reposilite.labels" . | nindent 4 }}
data:
  reposilite.cdn: |
{{ .Values.reposilite.config | b64enc | indent 8 }}
