apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reposilite.fullname" . }}-config
  labels:
    {{- include "reposilite.labels" . | nindent 4 }}
data:
  reposilite.cdn: |
{{ tpl ( .Files.Get "reposilite.cdn.tpl" ) . | b64enc | indent 8 }}
